name: wc_salary
description: "A toilet earnings tracker app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^7.0.1
  provider: ^6.0.5
  intl: ^0.20.2
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
  
  fonts:
    - family: RubikDirt
      fonts:
        - asset: assets/fonts/RubikDirt-Regular.ttf
