// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChGy9UkCA8LkssKjnHneBdkbUaRWSeEzA',
    appId: '1:325898949259:web:03c545ee5768dc7fe5ba8e',
    messagingSenderId: '325898949259',
    projectId: 'wc-salary',
    authDomain: 'wc-salary.firebaseapp.com',
    storageBucket: 'wc-salary.appspot.com',
    measurementId: 'G-B1SGY49LNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA_Mmnw5QSsi6ZpggavX-EvjtWiVHbV7Y',
    appId: '1:325898949259:android:7d0f7c9f879d14eee5ba8e',
    messagingSenderId: '325898949259',
    projectId: 'wc-salary',
    storageBucket: 'wc-salary.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6hUn9wnb2zIIp7fVffh8EsFRNHGIJpFc',
    appId: '1:325898949259:ios:6980750c00d935b6e5ba8e',
    messagingSenderId: '325898949259',
    projectId: 'wc-salary',
    storageBucket: 'wc-salary.appspot.com',
    iosClientId: '325898949259-72q7n9uem3pebgqmkl5kmaq263mggusi.apps.googleusercontent.com',
    iosBundleId: 'com.example.wcSalary',
  );
}
